import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainTitle from "./MainTitle"

import TestImg from "../public/Image/soonsoon.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Level Zero Test</title>
        <meta name="description" content="Generated by Level Zero Test"/>
      </Head>      
      
      <MainTitle/>
      <div>      
      <h3>Home</h3>
      <h4>1. 로그아웃시 팝업창으로 확인 취소 체크 </h4>
      <h4>2. Community에 게시판처럼 글작성해서 하단에 글 올려줘보기</h4>
      <h4>3. 스마트컨트랙트란? 무엇인지 찾아보기</h4>
      <h4>4. NFT 뉴스 페이지 제작</h4>
      <h4>5. 카이카스 지갑에서 전송 버튼 누르면, 보내지는 형태가 나오도록 해보기</h4>
      <h4>6. 게시판API Build 되게 수정</h4>
      <h4>7. 모달 팝업창 로그인되면 꺼지도록 만들기 </h4>
      <h4>8. 외부 함수 연결 하는 부분 확인하기 </h4>
      </div>
      
      <div className="HomeImageContainer">
        <Image src={TestImg}/>
      </div>
    </div>
  )
}
